# docker-compose.yml

services:
  db:
    image: postgres:14.8
    container_name: toolightb2b
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: toolight
      POSTGRES_PASSWORD: Bumelant#49!
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
