/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    categories: Category;
    'product-cards': ProductCard;
    manuals: Manual;
    'energy-labels': EnergyLabel;
    rma: Rma;
    banners: Banner;
    'main-menu': MainMenu;
    pos: Po;
    users: User;
    media: Media;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'product-cards': ProductCardsSelect<false> | ProductCardsSelect<true>;
    manuals: ManualsSelect<false> | ManualsSelect<true>;
    'energy-labels': EnergyLabelsSelect<false> | EnergyLabelsSelect<true>;
    rma: RmaSelect<false> | RmaSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    'main-menu': MainMenuSelect<false> | MainMenuSelect<true>;
    pos: PosSelect<false> | PosSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'top-bar': TopBar;
    'popular-categories': PopularCategory;
    'about-us': AboutUs;
    contact: Contact;
    footer: Footer;
    layout: Layout;
  };
  globalsSelect: {
    'top-bar': TopBarSelect<false> | TopBarSelect<true>;
    'popular-categories': PopularCategoriesSelect<false> | PopularCategoriesSelect<true>;
    'about-us': AboutUsSelect<false> | AboutUsSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    layout: LayoutSelect<false> | LayoutSelect<true>;
  };
  locale: 'pl';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  subiektId?: number | null;
  title: string;
  category?: (number | null) | Category;
  active?: boolean | null;
  new?: boolean | null;
  sale?: boolean | null;
  sku?: string | null;
  ean?: string | null;
  description?: string | null;
  /**
   * Generowany automatycznie na podstawie tytułu
   */
  slug?: string | null;
  b2bUrl?: string | null;
  attachments?: {
    energyLabel?: (number | null) | EnergyLabel;
    manual?: (number | null) | Manual;
    productCard?: (number | null) | ProductCard;
    otherAttachments?:
      | {
          name?: string | null;
          attachment?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  parameters?:
    | {
        name?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  mainImage?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        /**
         * Zaznacz, jeśli to zdjęcie ma być używane jako główne zdjęcie produktu
         */
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Generowany automatycznie na podstawie tytułu
   */
  slug?: string | null;
  relatedMainMenuLink: number | MainMenu;
  order: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    main?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu".
 */
export interface MainMenu {
  id: number;
  mainMenuLinkTitle?: string | null;
  mainMenuLinkUrl?: string | null;
  mainMenuOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "energy-labels".
 */
export interface EnergyLabel {
  id: number;
  /**
   * Produkt, do którego przypisana jest ta etykieta energetyczna
   */
  relatedProduct?: (number | null) | Product;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manuals".
 */
export interface Manual {
  id: number;
  /**
   * Produkt, do którego przypisana jest ta etykieta energetyczna
   */
  relatedProduct?: (number | null) | Product;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-cards".
 */
export interface ProductCard {
  id: number;
  /**
   * Produkt, do którego przypisana jest ta etykieta energetyczna
   */
  relatedProduct?: (number | null) | Product;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    main?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rma".
 */
export interface Rma {
  id: number;
  rmaId?: string | null;
  client?: {
    name?: string | null;
    phone?: string | null;
    company?: string | null;
    email?: string | null;
    address?: string | null;
    postalcode?: string | null;
    city?: string | null;
    nip?: string | null;
  };
  details?: {
    orderId?: string | null;
    description?: string | null;
    attachments?: (number | null) | Media;
  };
  status: 'Nowe' | 'Trwające' | 'Zakończone';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  title: string;
  active: boolean;
  /**
   * kolejność wyświetlania baneru
   */
  priority: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    main?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pos".
 */
export interface Po {
  id: number;
  name?: string | null;
  logo?: (number | null) | Media;
  addressLine1?: string | null;
  addressLine2?: string | null;
  openingHours?: {
    workingDays?: string | null;
    saturday?: string | null;
    sunday?: string | null;
  };
  contact?: {
    phone?: string | null;
    email?: string | null;
    location?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'product-cards';
        value: number | ProductCard;
      } | null)
    | ({
        relationTo: 'manuals';
        value: number | Manual;
      } | null)
    | ({
        relationTo: 'energy-labels';
        value: number | EnergyLabel;
      } | null)
    | ({
        relationTo: 'rma';
        value: number | Rma;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'main-menu';
        value: number | MainMenu;
      } | null)
    | ({
        relationTo: 'pos';
        value: number | Po;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  subiektId?: T;
  title?: T;
  category?: T;
  active?: T;
  new?: T;
  sale?: T;
  sku?: T;
  ean?: T;
  description?: T;
  slug?: T;
  b2bUrl?: T;
  attachments?:
    | T
    | {
        energyLabel?: T;
        manual?: T;
        productCard?: T;
        otherAttachments?:
          | T
          | {
              name?: T;
              attachment?: T;
              id?: T;
            };
      };
  parameters?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  mainImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        featured?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  relatedMainMenuLink?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        main?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-cards_select".
 */
export interface ProductCardsSelect<T extends boolean = true> {
  relatedProduct?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manuals_select".
 */
export interface ManualsSelect<T extends boolean = true> {
  relatedProduct?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "energy-labels_select".
 */
export interface EnergyLabelsSelect<T extends boolean = true> {
  relatedProduct?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rma_select".
 */
export interface RmaSelect<T extends boolean = true> {
  rmaId?: T;
  client?:
    | T
    | {
        name?: T;
        phone?: T;
        company?: T;
        email?: T;
        address?: T;
        postalcode?: T;
        city?: T;
        nip?: T;
      };
  details?:
    | T
    | {
        orderId?: T;
        description?: T;
        attachments?: T;
      };
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  title?: T;
  active?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        main?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu_select".
 */
export interface MainMenuSelect<T extends boolean = true> {
  mainMenuLinkTitle?: T;
  mainMenuLinkUrl?: T;
  mainMenuOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pos_select".
 */
export interface PosSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  addressLine1?: T;
  addressLine2?: T;
  openingHours?:
    | T
    | {
        workingDays?: T;
        saturday?: T;
        sunday?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        location?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        main?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "top-bar".
 */
export interface TopBar {
  id: number;
  topBar?: {
    topBarText?: string | null;
    languageSelect?: {
      topBarLocaleText?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popular-categories".
 */
export interface PopularCategory {
  id: number;
  popularCategories?:
    | {
        popularCategory?: (number | null) | Category;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us".
 */
export interface AboutUs {
  id: number;
  aboutUs?:
    | {
        icon?: (number | null) | Media;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  departments?:
    | {
        icon?: (number | null) | Media;
        title?: string | null;
        personel?:
          | {
              person?: string | null;
              function?: string | null;
              phone?: string | null;
              email?: string | null;
              id?: string | null;
            }[]
          | null;
        workingHours?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  address?: {
    companyName?: string | null;
    address?: string | null;
    postalCode?: string | null;
    city?: string | null;
    nip?: string | null;
  };
  privacy?: {
    title?: string | null;
    terms?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layout".
 */
export interface Layout {
  id: number;
  header?: {
    searchPlaceholder?: string | null;
    searchPlaceholderDropdown?: string | null;
    noProducts?: string | null;
    showAll?: string | null;
  };
  banners: {
    bannerAutoplay?: boolean | null;
    /**
     * w sekundach
     */
    bannerAutoplayDelay: number;
  };
  sections?: {
    popularCategories?: string | null;
    aboutUs?: string | null;
    contact?: string | null;
    homePage?: string | null;
  };
  contact?: {
    colaborationTitle?: string | null;
    colaborationDescription?: string | null;
    contactForm?: {
      contactCompany?: string | null;
      contactCity?: string | null;
      contactPostalCode?: string | null;
      contactMail?: string | null;
      contactPhone?: string | null;
      contactText?: string | null;
      contactRequiredText?: string | null;
      contactCta?: string | null;
    };
    contactDetails?: {
      workingHours?: string | null;
    };
  };
  products?: {
    parameters?:
      | {
          name?: string | null;
          id?: string | null;
        }[]
      | null;
    productHeading?: string | null;
    productCount?: string | null;
    productListingView?: string | null;
    productTagNew?: string | null;
    productTagSale?: string | null;
    productBtnCard?: string | null;
    productBtnPrice?: string | null;
    productDetails?: string | null;
    productDescription?: string | null;
    productDownload?: string | null;
    noProducts?: string | null;
    listing?: {
      nextPage?: string | null;
      prevPage?: string | null;
      pages?: string | null;
      from?: string | null;
    };
  };
  pos?: {
    heading?: string | null;
    searchPlaceholder?: string | null;
    locationPlaceholder?: string | null;
  };
  support?: {
    heading?: string | null;
    searchPlaceholder?: string | null;
    downloadBtn?: string | null;
  };
  other: {
    notFound?: string | null;
    defaultCategoryPage: number | MainMenu;
  };
  email: {
    host: string;
    port: string;
    senderEmail: string;
    password: string;
    senderName: string;
    subject: string;
    senderReplay: {
      subject: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "top-bar_select".
 */
export interface TopBarSelect<T extends boolean = true> {
  topBar?:
    | T
    | {
        topBarText?: T;
        languageSelect?:
          | T
          | {
              topBarLocaleText?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popular-categories_select".
 */
export interface PopularCategoriesSelect<T extends boolean = true> {
  popularCategories?:
    | T
    | {
        popularCategory?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us_select".
 */
export interface AboutUsSelect<T extends boolean = true> {
  aboutUs?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  departments?:
    | T
    | {
        icon?: T;
        title?: T;
        personel?:
          | T
          | {
              person?: T;
              function?: T;
              phone?: T;
              email?: T;
              id?: T;
            };
        workingHours?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  address?:
    | T
    | {
        companyName?: T;
        address?: T;
        postalCode?: T;
        city?: T;
        nip?: T;
      };
  privacy?:
    | T
    | {
        title?: T;
        terms?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layout_select".
 */
export interface LayoutSelect<T extends boolean = true> {
  header?:
    | T
    | {
        searchPlaceholder?: T;
        searchPlaceholderDropdown?: T;
        noProducts?: T;
        showAll?: T;
      };
  banners?:
    | T
    | {
        bannerAutoplay?: T;
        bannerAutoplayDelay?: T;
      };
  sections?:
    | T
    | {
        popularCategories?: T;
        aboutUs?: T;
        contact?: T;
        homePage?: T;
      };
  contact?:
    | T
    | {
        colaborationTitle?: T;
        colaborationDescription?: T;
        contactForm?:
          | T
          | {
              contactCompany?: T;
              contactCity?: T;
              contactPostalCode?: T;
              contactMail?: T;
              contactPhone?: T;
              contactText?: T;
              contactRequiredText?: T;
              contactCta?: T;
            };
        contactDetails?:
          | T
          | {
              workingHours?: T;
            };
      };
  products?:
    | T
    | {
        parameters?:
          | T
          | {
              name?: T;
              id?: T;
            };
        productHeading?: T;
        productCount?: T;
        productListingView?: T;
        productTagNew?: T;
        productTagSale?: T;
        productBtnCard?: T;
        productBtnPrice?: T;
        productDetails?: T;
        productDescription?: T;
        productDownload?: T;
        noProducts?: T;
        listing?:
          | T
          | {
              nextPage?: T;
              prevPage?: T;
              pages?: T;
              from?: T;
            };
      };
  pos?:
    | T
    | {
        heading?: T;
        searchPlaceholder?: T;
        locationPlaceholder?: T;
      };
  support?:
    | T
    | {
        heading?: T;
        searchPlaceholder?: T;
        downloadBtn?: T;
      };
  other?:
    | T
    | {
        notFound?: T;
        defaultCategoryPage?: T;
      };
  email?:
    | T
    | {
        host?: T;
        port?: T;
        senderEmail?: T;
        password?: T;
        senderName?: T;
        subject?: T;
        senderReplay?:
          | T
          | {
              subject?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}